### ISSUE TITLE
Настроить CI

### ISSUE THREAD

**Issue by Gordon-F** [ruRust/cargo-docs-ru#2]

**Comment by Gordon-F** [comment]
Done

**Comment by mkpankov** [comment]
А куда деплоится? Ссылка есть?

**Comment by Gordon-F** [comment]
@mkpankov https://rurust.github.io/cargo-docs-ru/

**Comment by mkpankov** [comment]
Надо бы её добавить на сайт куда-то

**Comment by Gordon-F** [comment]
В разделе книги ?

**Comment by mkpankov** [comment]
Не, в книги не в тему.

Заведи пожалуйста в rustycrate.ru задачу на добавление этой ссылки, я подумаю как там реорганизовать меню и сделаю.

**Comment by Gordon-F** [comment]
Ок
